### ISSUE TITLE
App: Tlk.io

### ISSUE THREAD

**Issue by Brayman30** [atomery/catalog#104]
name: "Tlk.io"
url: "Tlk.io"
Category: "Social Networking"
Icon: 
![download](https://user-images.githubusercontent.com/33497147/83821710-1aec6e00-a69d-11ea-94c1-5a8050964646.png)

**Comment by Brayman30** [comment]
As for the Icon... I could not find any Icons above 100px x 100px I emailed them and will post a new one or their response when I get a response back...

**Comment by quanglam2807** [comment]
Thank you for submitting! I found the icon
