### ISSUE TITLE
Change the GitHub icon to the official one for the website to differentiate the WebApp from the GitHub Desktop App

### ISSUE THREAD

**Issue by surferking** [atomery/catalog#92]
- https://images.app.goo.gl/dkT8AWGH6BPMD8Ys5

![image](https://user-images.githubusercontent.com/6428977/79919023-77653800-8425-11ea-8c32-883a8ff77553.png)

**Comment by surferking** [comment]
Maybe a bug, maybe a cache issue, I got this error when deleting and reinstalling the GitHub App:

<img width="1569" alt="Screenshot 2020-04-22 at 18 15 13" src="https://user-images.githubusercontent.com/6428977/80012633-83a0d200-84c5-11ea-99e4-1b918bc6b4ba.png">

**Comment by quanglam2807** [comment]
Probably caching. Does it work now?
